# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# RuboCopのアップデートにより自動でルールを追加しないように設定
AllCops:
  NewCops: disable

# 以下のルールだけ明示的に追加
Lint:
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  Max: 20
