services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  bundle_data:
  postgresql_data:
